config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, presence: true
  validates_uniqueness_of :list_id, :scope => [:movie_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, :dependent => :delete_all
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true,presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to root_path(@list)
   else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to root_path(@bookmark.list)
  end

  private
  
  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end
  
  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class= "container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.all.order(:title) %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LISTOVIES</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "bg-color-gray">
  <div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/parcials/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1595769816263-9b910be24d5f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2079&q=80);">
  <div class="nav-banner">
  </div>
  <div class="container banner-text">
    <h1>Welcome to <strong>LISTOVIES</strong> where <strong>all your lists can come true</strong>!</h1>
    <p>Lists + Movies = LISTOVIES</p>
    <%= link_to "Create a Listovie", new_list_path, class: "btn-flat" %>
  </div>
</div>

app/views/layouts/parcials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to lists_path, class: "navbar-brand" do %>
  <div class= >
    <strong><p class= "text-nav pt-3 px-3" ><%= "Listovies" %></p></strong>
  </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <strong><%= link_to "My Lists", lists_path, class: "nav-link" %></strong>
      </li>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "layouts/parcials/banner" %>
<div>
  <div class= "cards container my-5">
    <% @lists.each do |list| %>
      <div>
        <div class="card-category-index" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1598814996357-799cbb953998?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)">
          <%= link_to list.name, list_path(list) %>
        </div>
        <div class ="delete-link text-center bg-danger color text-decoration-none">
          <%= link_to "Delete", list_path(list), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class= "container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class=  "container">
  <%= render "layouts/parcials/navbar" %>
</div>
<div class="banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1597002973885-8c90683fa6e0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1164&q=80);">
  <div class="container">
    <h1 class= ""><strong><%= @list.name %></strong></h1>
  </div>
</div>
<div>

  <%= link_to "New Bookmark", new_list_bookmark_path(@list), class: "btn btn-flat m-4" %>

   <div class= "cards container my-5">
    <% @list.bookmarks.each do |bookmark| %>
      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( '<%= bookmark.movie.poster_url %>' )">
          <%= bookmark.movie.title %>
        </div>
        <div>
          
        </div>
        <div class ="delete-link text-center bg-danger color text-decoration-none">
          <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-button" %>
        </div>
      </div>
    <% end %>
  </div>

</div>